version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onboarding_database
    networks:
      - onboarding

  dev-mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: onboarding_mongo
    networks:
      - onboarding

networks:
  onboarding:
