version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onboarding_database
    networks:
      - onboarding
  dev-cache:
    image: redis:latest
    ports:
      - '6371:6379'
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - cache:/data
networks:
  onboarding:
volumes:
  cache:
    driver: local
